### ISSUE TITLE
Time consumming workflow 

### ISSUE THREAD

**Issue by DariuszKruszka** [eMetaboHUB/MS-CleanR#11]
Hi @guikool, @gcabanac, @SyrupType 
I'd like to ask you about workflow for pos and neg ionisation. 
I've got experiment with 60 samples in neg mode and 60 in pos mode. My computer (i9-10900X CPU @ 3.70GHz /64GB RAM) was processing this data set very long. How can I improve this process? I added settings for first step.
Best regards
Darek
![Zrzut ekranu_20230109_102630](https://user-images.githubusercontent.com/73880130/211276832-1504eb05-4e46-4faa-8871-4df47f4de0ec.png)

**Comment by guikool** [comment]
Dear Darius,
sorry for the late reply
indeed it will largely depend on dataset size in input
For instance, if the output from MSdial are above thousands of features, it may be very long.
As a rule of thumb, for orbitrap, use 100000 to 500000 as threshold value in MSdial, use 1000 to 10000 for QTOF based detector.
If you encounter more than 1000 features after MSdial, increase your threshold.
Best regards
G.

**Comment by guikool** [comment]
Another thing to consider is your feature RSD treshold set at "80" which seems really high, a value around "40" is more suitable
