### ISSUE TITLE
Publish as package on CRAN or bioconda

### ISSUE THREAD

**Issue by hechth** [eMetaboHUB/MS-CleanR#12]
Hi! To make this package available to more people and easy to access and install, it would be great if the package could be published on [CRAN](https://cran.r-project.org/web/packages/policies.html) or [bioconda](https://bioconda.github.io/contributor/index.html).

Together with that, it also makes sense to introduce [versioning](https://semver.org/spec/v2.0.0.html) so that people can reproducibly process their data.

**Comment by hechth** [comment]
@guikool @SyrupType @gcabanac

**Comment by SyrupType** [comment]
Hello @hechth , you make a really good point but unfortunately I’m not actively working on the project anymore (I developed it a few years ago and changed job since), and my comrades are short on time.
I’ll try to look at how to publish it properly on CRAN when I have a bit of time.

**Comment by hechth** [comment]
@SyrupType is there anyone still working on this or does your institute where you published this have some department responsible for research software? Maybe they could help out?

If there is a large enough community of interested users I'm sure there could be resources found for this from various community members.

**Comment by guikool** [comment]
@hechth thanks for your notifications, although we try to answer people who need some help, this package will be replaced soon by a completely new version. 
As you suggested, we will push for an open source licence.
Best regards
G.

**Comment by hechth** [comment]
Hi, would be great if the repository would already be made public to have people be aware and also to get community involvement. Also, please mark this repository as archive to indicate that it is no longer maintained. Please reach out to me if you want any support with getting the new version onto CRAN or bioconda or PyPI strait away. Thanks! Best, Helge
