### ISSUE TITLE
Duplicated results - error

### ISSUE THREAD

**Issue by DariuszKruszka** [eMetaboHUB/MS-CleanR#14]
Hi
I used your packed for processing of negative ion mode data. I have 130 samples in several groups (~30). 
I applied commend:
**clean_msdial_data**( filter_blk = T, filter_blk_threshold = 0.9, filter_blk_ghost_peaks = T, filter_mz = T, filter_rsd = T, filter_rsd_threshold = 200, filter_rmd = T, filter_rmd_range = c(50, 3000), threshold_mz = 0.01, threshold_rt = 0.1, user_pos_adducts_refs = NA, user_neg_adducts_refs = NA, user_pos_neutral_refs = NA, user_neg_neutral_refs = NA, compute_pearson_correlation = T, pearson_correlation_threshold = 0.97, pearson_p_value = 0.01)
and  I got this information
Warning messages:
1: In type.convert.default(unlist(x, use.names = FALSE)) :
  'as.is' should be specified by the caller; using TRUE
2: In merge.data.frame(peak_data, height_data[, c("id", "ratio_Blank")],  :
  column names ‘Z.1’, ‘Z.1’, ‘Z.1’, ‘Z.1’, ‘Z.1’, ‘Z.1’, ‘Z.1’, ‘Z.1’, ‘B.1’, ‘Q.1’, ‘Z.2’, ‘Z.2’, ‘Z.2’, ‘B.2’, ‘Z.2’, ‘Q.2’, ‘Z.2’, ‘Z.2’, ‘Z.2’, ‘Z.2’, ‘Z.3’, ‘Z.3’, ‘Z.3’, ‘Z.3’, ‘Z.3’, ‘Z.3’, ‘B.3’, ‘Z.3’, ‘Z.3’, ‘Q.3’ are duplicated in the result
3: In merge.data.frame(peak_data, ghosts, by = "round_mz") :
  column names ‘Z.1’, ‘Z.1’, ‘Z.1’, ‘Z.1’, ‘Z.1’, ‘Z.1’, ‘Z.1’, ‘Z.1’, ‘B.1’, ‘Q.1’, ‘Z.2’, ‘Z.2’, ‘Z.2’, ‘B.2’, ‘Z.2’, ‘Q.2’, ‘Z.2’, ‘Z.2’, ‘Z.2’, ‘Z.2’, ‘Z.3’, ‘Z.3’, ‘Z.3’, ‘Z.3’, ‘Z.3’, ‘Z.3’, ‘B.3’, ‘Z.3’, ‘Z.3’, ‘Q.3’ are duplicated in the result
 
Unfortunetly, I got in next step: 
Error in `[<-.data.frame`(`*tmp*`, samples$Column_name, value = c(0.000193764208962931,  : 
repeted index for column
when I applied **launch_msfinder_annotation**

Do you know how can I fix this problem? 

Best regards 
Darek

**Comment by DariuszKruszka** [comment]
Dear @guikool 
Do you know the solution to the problem?

**Comment by guikool** [comment]
Dear Darek
I'm sorry, but we no longer maintain MScleanR anymore (I'll add the message on the main page).
I advise you to run the last MSdial version (>5) and apply for MScleanR filtering (which correspond to the first step of MScleanR) then export only filtered features.
We are cooking a new version which will take into account all MSDial5 new features and publish it at the beginning of next year.
Best
G.
