### ISSUE TITLE
 Help with Data Input and Processing in MS-CleanR from Agilent .D Format

### ISSUE THREAD

**Issue by Javi-Rop** [eMetaboHUB/MS-CleanR#15]
Hello everyone,

I'm seeking guidance and assistance with introducing and processing data in the .D format generated by Agilent instruments in MS-CleanR. I would greatly appreciate it if someone could provide information on the format and file extension of data files that are compatible with MS-CleanR and how to carry out the conversion and processing of .D files in this tool.

Additionally, I have encountered the following error when attempting to load the data into MS-CleanR:

Error: A pos or a neg directory must be present. Check your data and your parameters. If the problem persists, you can contact [guillaume.marti@univ-tlse3.fr](mailto:guillaume.marti@univ-tlse3.fr).

My main questions include:

What is the required format and file extension for data input in MS-CleanR?

What is the recommended process for converting .D files generated by Agilent instruments into formats compatible with MS-CleanR, such as .mzML, .mzXML, or .cdf?

Are there specific steps or recommendations for preparing and organizing data before loading it into MS-CleanR?

Any information, resources, or examples related to data input and processing in MS-CleanR would be greatly appreciated by me and other community members who may have the same question.

Thank you in advance for your cooperation and assistance!

Best regards,
Javier Rodríguez

**Comment by guikool** [comment]
Please, read the tutorial from github repo,
All data must be processed through MSDial 4.x
