### ISSUE TITLE
Error in Negative mode

### ISSUE THREAD

**Issue by ykim7263** [eMetaboHUB/MS-CleanR#2]
Hi,

I have tried running MS-Clean R with my MS Dial data.
I have both positive and negative datasets and I am trying to use them separately
Everything went well with the positive mode data set. But the error popped up whenever i tried to use the negative data set.
The error is described below.

Warning: Error in $<-.data.frame: replacement has 0 rows, data has 30997
  [No stack trace available]

**Comment by guikool** [comment]
Please check the previously closed issue
most of the errors come from no MS/MS data available in one of the scan mode (here probably negative) 
If you try to merge pos and neg mode, be careful to have exactly the same samples number in the same order in MS-Dial
in case, send me the output files of MSdial on the email of the MScleanR corresponding author.
Best regards
G.

**Comment by ykim7263** [comment]
Normalized_1_20212151651_pos.txt
<https://drive.google.com/file/d/1IBB6OI_ZUKsD6S1k35Sx7sL_oIKXYQbH/view?usp=drive_web>
 Normalized_0_20212142141_neg.txt
<https://drive.google.com/file/d/1APvfw8sn-tPA9FPHDqF_0TqmCsrUWgkH/view?usp=drive_web>
Hi all,

I have checked my data and it contains MS2 scan on both polarities
(Acquired by data dependent acquisition method)
For your better understanding, I have attached aligned result files from
both polarities.
Just FYI, I really appreciate you for developing this software.

Best regards
Kim

**Comment by guikool** [comment]
Dear Kim
According to the size of .txt files, I think R cannot handle this data, its too big...

To my mind you need to increase the baseline treshold in MSdial (minimum peak height), its a critical parameter as noticed in our tutorial.

If you use an orbitrap, test it between 1e6 to 5e6, for TOFMS you can try between 5000 and 10 000.

For complex samples, a feature number between 500 and 2000 is usual (for the height file after MSdial processing), if you exceed this number, you may reconsider your MSdial parameters.

Best

G.

**Comment by ykim7263** [comment]
Hi,

I have modified the MSDIAL parameter, but it still shows the same error. 
It does work well with positive mode, even though it has a higher file size.

Best regard,
Kim

**Comment by ykim7263** [comment]
Just want to let you know I solve the problem with the negative mode error, so you can close the error.
I have done two things, first I downgraded the vroom. 
Also, I overwrote the negative data (Height and normalized) onto the txt file generated from the positive mode.
