### ISSUE TITLE
Error: only 0's may be mixed with negative subscripts

### ISSUE THREAD

**Issue by villekoi** [eMetaboHUB/MS-CleanR#3]
Hello,

I am getting an error message "only 0's may be mixed with negative subscripts" during the clean MS-DIAL data step after a couple of minutes from starting the process. Does someone have an idea what kind of problem this indicates? I tried to start a new session in RStudio with cleaned environment.

Thank you,
Ville

**Comment by guikool** [comment]
Dear Ville
This is an unknown error message encountered so far
please send me your .txt files from MSdial (Height and normalized) so I'll check on my side
(guillaume.marti@univ-tlse3.fr)
G.
