### ISSUE TITLE
Example parameter file

### ISSUE THREAD

**Issue by XinsongDu** [eMetaboHUB/MS-CleanR#4]
Is there an example parameter file that can be used to run MSClean-R? I found the parameter file exported from MS-DIAL v4.48 couldn't be recognized by the tool. Thanks in advance!

**Comment by XinsongDu** [comment]
<img width="907" alt="Screen Shot 2021-02-25 at 11 43 16 AM" src="https://user-images.githubusercontent.com/16085076/109186200-ac859980-775e-11eb-832c-c6ef37964b65.png">

**Comment by guikool** [comment]
At the end of the MScleanR process, you can save all used parameters and recall this file for new analysis. You can do the same for MSdial project but within MSdial.
