### ISSUE TITLE
Error: replacement has 1 row, data has 0

### ISSUE THREAD

**Issue by tbento2015** [eMetaboHUB/MS-CleanR#7]
Hello, I am having a problem using the MScleanR generic filtration step from MS-DIAL export files because I continue to get the following Warning: Error in $<-.data.frame: replacement has 1 row, data has 0 [No stack trace available].

I ensured that groups were appropriately assigned during MS-DIAL analysis and that the alignment export reflects this.

Thanks in advance for your help!

**Comment by guikool** [comment]
Hi
this error arise when there is no MS/MS data available, since MS-CleanR is for all ion fragmentation method.
Did you acquire the data in DIA or DDA mode?

**Comment by tbento2015** [comment]
Hi, 
yes, my data is in DDA mode.

**Comment by guikool** [comment]
did you check the sample order (must be exactly the same) as for sample number and groups between pos and neg

**Comment by guikool** [comment]
otherwise, send me your output files from MSDIAL so I'll check your data (guillaume.marti@univ-tlse3.fr)

**Comment by tbento2015** [comment]
Hi,  I just sent it to you. Please let me know if you need anything else.

**Comment by guikool** [comment]
Indeed QC should represent a mixture of all your sample
try to name three Ctrl as QC and keep three other as Ctrl and name them accordingly in the class column.

Also change the name of your sample by adding a letter before the number and remove the « _ » at the end.

If it doesn’t work, I don’t figure out what’s happening with your data.
Best,
G.
