### ISSUE TITLE
Intensity of compund in each group in annotated_MS_peaks-cleaned.csv is far from that in raw data

### ISSUE THREAD

**Issue by g0079** [eMetaboHUB/MS-CleanR#9]
Hi,  I'am using MS-CleanR to deal with metabonnomics data. It's very convenient to do data clean after MS-DIAL data processing. But I found that the intensity of compund in each group in annotated_MS_peaks-cleaned.csv is far different from that in raw data, for example, the intensity in Height_xxx.txt exported from MS-DIAL. I would like to know what kind of operations was implemented by ms-cleanR to the raw intensity, and whether there is a way to keep the raw intensity in the output of ms-cleanR. Thank you very much.

**Comment by guikool** [comment]
Dear user,
Tow files are generated after MSCleanR data processing:
annotated_MS_peaks_normalized: the normalization is done according to "sum area" of each feature. Meaning that each sample will have an identical total sum area -->suitable for further statistical analysis
annotated_MS_peaks_cleaned: Correspond to integration done by MS-Dial: suitable to apply your own normalization process (in metaboanalyst for instance)

**Comment by g0079** [comment]
Now I,m sure no log transformation was applied on the raw data, Thank you!
